import { ArrowRight, ArrowUpRight, Leaf, ShieldCheck, Activity, Grid2X2, Boxes, Database, CircleCheck, Clock3, Workflow, ScanLine } from 'lucide-react';
import type { Workspace,Page } from '../types';
import {connectedContext,riskInputs} from '../lib/cube-context.mjs';
import { aggregate } from '../lib/portfolio.mjs';
import { calculateECL } from '../lib/risk.mjs';
import { money,pct,compact } from '../lib/format';
import { Panel,Next } from '../components/UI';
const modules=[{page:'esg',n:'01',icon:Leaf,title:'ESG intelligence',tag:'Impact & evidence',description:'Connect sustainability assessments, financed emissions and green finance.',cta:'Explore sustainability'}, {page:'stress',n:'02',icon:Activity,title:'Stress laboratory',tag:'Resilience & scenarios',description:'Trace shocks from credit losses through earnings, capital and headroom.',cta:'Build a scenario'},{page:'ecl',n:'03',icon:ShieldCheck,title:'IFRS 9 workspace',tag:'Stage · Measure · Explain',description:'Follow probability-weighted loss from each facility to your portfolio.',cta:'Calculate expected loss'},{page:'pivot',n:'04',icon:Grid2X2,title:'Pivot Desk',tag:'Explore & reconcile',description:'Shape your own portfolio views and explain every control difference.',cta:'Open the desk'}] as const;
export default function Desk({workspace:w,navigate}:{workspace:Workspace,navigate:(p:Page)=>void}){
 const cube=connectedContext(w.facilities,w.settings); const total=w.facilities.reduce((s,f)=>s+f.balance,0),green=w.facilities.filter(f=>f.green).reduce((s,f)=>s+f.balance,0),score=total?w.facilities.reduce((s,f)=>s+f.esgScore*f.balance,0)/total:0; const inputs=riskInputs(w.facilities,w.settings);const ecl=calculateECL(inputs.facilities,w.settings.eclScenarios as Parameters<typeof calculateECL>[1]);const groups=aggregate(w.facilities,'sector','balance'); const max=Math.max(1,...groups.map(g=>g.value)); const flags=ecl.facilities.filter(f=>f.stage>1).length;
 return <><section className="hero"><div className="hero-pattern"/><div className="hero-copy"><div className="eyebrow"><span className="live-dot"/>Connected intelligence / One Avati</div><h1>One portfolio.<br/><span>Every perspective.</span></h1><p>Follow the scenario from risk signals to credit loss,<br/>capital, liquidity and a reconciled decision.</p><div className="button-row"><button className="btn primary" onClick={()=>navigate('cube')}>Open RiskCube<ArrowRight size={17}/></button><button className="btn hero-secondary" onClick={()=>navigate('portfolio')}><Database size={16}/>Open portfolio</button></div><div className="hero-foot"><CircleCheck size={14}/>{w.facilities.length} facilities connected<span>·</span>Portfolio v{w.portfolioVersion}<span>·</span>USD millions</div></div><div className="hero-kpis"><div className="hero-kpi"><div><span>Portfolio exposure</span><Database size={16}/></div><strong>${money(total/1000,2)}<small>bn</small></strong><p>{new Set(w.facilities.map(f=>f.sector)).size} sectors · {new Set(w.facilities.map(f=>f.country)).size} markets</p><div className="segments">{[1,2,3,4,5,6,7].map(n=><i key={n}/>)}</div></div><div className="hero-kpi"><div><span>Expected credit loss</span><ShieldCheck size={16}/></div><strong>{inputs.error?'—':`$${money(ecl.weightedEcl)}`}<small>{inputs.error?'Blocked':'m'}</small></strong><p>{inputs.error?'RiskCube calibration needs attention':`${pct(total?ecl.weightedEcl/total:0)} of drawn exposure · current ECL settings`}</p><div className="bar-track"><div className="bar-fill" style={{width:`${inputs.error?0:Math.min(100,ecl.coverage*100)}%`}}/></div></div><div className="hero-kpi"><div><span>ESG portfolio score</span><Leaf size={16}/></div><strong>{score.toFixed(0)}<small>/100</small></strong><p>Exposure-weighted input score</p><div className="bar-track"><div className="bar-fill" style={{width:`${score}%`}}/></div></div><div className="hero-kpi"><div><span>Green candidates</span><Workflow size={16}/></div><strong>{pct(total?green/total:0,0)}</strong><p>Subject to taxonomy evidence review</p><div className="bar-track"><div className="bar-fill" style={{width:`${total?100*green/total:0}%`}}/></div></div></div></section>
 <section className="cube-home"><div className="cube-home-intro"><span className="cube-home-icon"><Boxes size={24}/></span><div><div className="eyebrow">The connected engine</div><h2>Every change has a consequence.</h2><p>Portfolio → ESG context → scenario → PD / LGD → ECL → capital → liquidity</p></div></div>{cube.result?<div className="cube-home-values"><div><small>Incremental credit loss</small><strong>${money(cube.result.capital.creditLoss)}m</strong></div><div><small>Stressed capital ratio</small><strong>{pct(cube.result.capital.carAfter)}</strong></div><div><small>Liquidity coverage proxy</small><strong>{pct(cube.result.liquidity.lcrAfter)}</strong></div></div>:<p className="muted">Review the model connection to resolve the blocked run.</p>}<button className="btn" onClick={()=>navigate('cube')}>Follow the connections<ArrowRight size={15}/></button></section><div className="section-heading"><div><div className="eyebrow">Your connected workspace</div><h2>From insight to a considered decision.</h2></div><span className="subtle-badge"><span className="live-dot"/>4 modules · 1 portfolio</span></div>
 <div className="module-grid">{modules.map(m=><button key={m.page} className="module-card" onClick={()=>navigate(m.page)}><div className="module-top"><span className="step-number">{m.n}</span><m.icon size={22}/></div><div className="eyebrow">{m.tag}</div><h3>{m.title}</h3><p>{m.description}</p><div className="module-link">{m.cta}<ArrowUpRight size={17}/></div></button>)}</div>
 <div className="desk-lower"><Panel title="Portfolio composition" subtitle="Drawn exposure by sector · USD millions" action={<Next onClick={()=>navigate('pivot')}>Explore</Next>}><div className="composition-chart">{groups.slice(0,6).map((g,i)=><div className="chart-row" key={g.key}><div><span><i className={`chart-dot tone-${i%3}`}/>{g.key}</span><strong>{money(g.value,0)}<small>{pct(total?g.value/total:0)}</small></strong></div><div className="bar-track"><div className={`bar-fill tone-${i%3}`} style={{width:`${100*g.value/max}%`}}/></div></div>)}</div></Panel><Panel title="On your radar" subtitle="A focused view of what needs your attention." action={<ScanLine size={19}/>}><button className="radar-row" onClick={()=>navigate('ecl')}><span className="radar-icon warn"><ShieldCheck size={19}/></span><div><strong>{flags} facilities need a closer look</strong><p>Delinquency or watchlist flags in your master.</p></div><ArrowUpRight size={16}/></button><button className="radar-row" onClick={()=>navigate('esg')}><span className="radar-icon"><Leaf size={19}/></span><div><strong>Evidence makes the difference</strong><p>Review green candidates before making a claim.</p></div><ArrowUpRight size={16}/></button><button className="radar-row" onClick={()=>navigate('reports')}><span className="radar-icon"><Clock3 size={19}/></span><div><strong>{w.runs.length?`${w.runs.length} saved analyses`:'Start your first review pack'}</strong><p>{w.runs.length?'Open snapshots, compare runs and export results.':'Capture a model run to begin your reporting history.'}</p></div><ArrowUpRight size={16}/></button><div className="desk-note"><span className="live-dot"/>Your workspace stays on this device.<br/><small>Export a workspace backup to move it safely.</small></div></Panel></div>
 <div className="demo-strip"><span>ILLUSTRATIVE WORKSPACE</span><p>Synthetic portfolio · Configurable planning models · Independent validation required for bank use</p><button onClick={()=>navigate('activity')}>View lineage <ArrowRight size={14}/></button></div></>;
}
