import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Check, ChevronDown, FileCheck2, Info, Save, Search } from 'lucide-react';
import type { ModuleProps } from '../types';
import { calculateECL, DEFAULT_ECL_SCENARIOS, validateScenarioWeights } from '../lib/risk.mjs';
import { Metric, PageHeader } from '../components/UI';

type Scenario = typeof DEFAULT_ECL_SCENARIOS[number];
function readScenarios(raw:unknown):{scenarios:Scenario[];error:string|null} {
  const fallback=DEFAULT_ECL_SCENARIOS.map(s=>({...s}));
  if(raw===undefined) return {scenarios:fallback,error:null};
  if(!Array.isArray(raw)||raw.length===0||raw.some(s=>!s||typeof s!=='object'||typeof s.id!=='string'||!s.id.trim()||typeof s.name!=='string'||!s.name.trim()||typeof s.weight!=='number'||!Number.isFinite(s.weight)||typeof s.pdMultiplier!=='number'||!Number.isFinite(s.pdMultiplier))||new Set(raw.map(s=>s.id)).size!==raw.length) return {scenarios:fallback,error:'Saved ECL scenarios contain missing or invalid records.'};
  return {scenarios:raw.map(s=>({...s})),error:null};
}
const money = (value:number) => `$${value.toLocaleString('en-US', { maximumFractionDigits: 2 })}m`;
const pct = (value:number) => `${(value*100).toFixed(2)}%`;

export default function ECL({ facilities, settings, saveSetting, onRun }:ModuleProps) {
  const stored=useMemo(()=>readScenarios(settings.eclScenarios),[settings.eclScenarios]);
  const [scenarios, setScenarios] = useState<Scenario[]>(stored.scenarios);
  const [loadError,setLoadError]=useState(stored.error);
  const [stageFilter, setStageFilter] = useState(0);
  const [search, setSearch] = useState('');
  const [selected, setSelected] = useState(facilities[0]?.id||'');
  const [scenarioId, setScenarioId] = useState('baseline');
  const [page, setPage] = useState(0);
  const [saved, setSaved] = useState(false);
  useEffect(()=>{setScenarios(stored.scenarios);setLoadError(stored.error);setSaved(false);},[stored]);
  useEffect(()=>{setSaved(false);setPage(0);},[facilities]);
  const calculation = useMemo(()=> {
    try { return { result:calculateECL(facilities,scenarios), error:null }; }
    catch(error) { return { result:null, error:error instanceof Error ? error.message : 'Check portfolio inputs.' }; }
  }, [facilities, scenarios]);
  const result = calculation.result;
  const weightsError = validateScenarioWeights(scenarios);
  const totalWeight=scenarios.reduce((sum,s)=>sum+s.weight,0);
  const filtered = result?.facilities.filter(f=>(!stageFilter||f.stage===stageFilter)&&`${f.id} ${f.borrower} ${f.sector}`.toLowerCase().includes(search.toLowerCase())) || [];
  const safePage = Math.min(page, Math.max(0,Math.ceil(filtered.length/8)-1));
  const current = result?.facilities.find(f=>f.id===selected)||result?.facilities[0];
  const trace = current?.scenarios.find(s=>s.id===scenarioId)||current?.scenarios[0];
  function updateScenario(id:string, key:'weight'|'pdMultiplier', value:number) {
    const next=scenarios.map(s=>s.id===id?{...s,[key]:value}:s);
    setScenarios(next); setSaved(false);
    if(!validateScenarioWeights(next)) saveSetting('eclScenarios',next);
  }
  function reset(){const next=DEFAULT_ECL_SCENARIOS.map(s=>({...s}));setScenarios(next);setLoadError(null);setSaved(false);saveSetting('eclScenarios',next);}
  function saveRun() {
    if (!result||loadError) return;
    onRun({ module:'ECL',name:'Probability-weighted ECL assessment',summary:{'Weighted ECL (USDm)':result.weightedEcl,'Exposure at default (USDm)':result.ead,'Coverage (%)':result.ead?Number((result.coverage*100).toFixed(2)):'Unavailable'},payload:result });
    setSaved(true);
  }
  if(loadError) return <><PageHeader eyebrow="CREDIT INTELLIGENCE / IFRS 9" title="Expected credit loss" description="Review the saved scenarios before continuing."/><section className="panel"><h2>ECL settings need attention</h2><p className="notice bad" role="alert">{loadError}</p><p className="muted">Your portfolio and saved reports remain intact. Reset the ECL scenarios to the illustrative baseline, upside and downside assumptions to continue.</p><button className="btn primary" onClick={reset}>Reset ECL scenarios</button></section></>;
  return <>
    <PageHeader eyebrow="CREDIT INTELLIGENCE / IFRS 9" title="Expected credit loss" description="From each staging decision to a probability-weighted loss." action={<button className="btn primary" onClick={saveRun} disabled={!result}>{saved?<Check size={16}/>:<Save size={16}/>} {saved?'Snapshot saved':'Save assessment'}</button>}/>
    {calculation.error&&<div className="notice bad" role="alert"><span>{calculation.error} Incomplete edits are not saved.</span><button className="btn small" onClick={reset}>Reset scenarios</button></div>}
    <div className="metrics"><Metric label="Weighted ECL" value={result?money(result.weightedEcl):'—'} detail={`${scenarios.length} economic outlooks`}/><Metric label="Exposure at default" value={result?money(result.ead):'—'} detail="Drawn + converted undrawn"/><Metric label="ECL coverage" value={result?.ead?pct(result.coverage):'—'} detail="Weighted ECL / EAD"/><Metric label="Credit-impaired facilities" value={result?.stageTotals[2].count??'—'} detail="Including borrower contagion"/></div>
    <div className="grid-2"><section className="panel"><div className="panel-header"><div><div className="eyebrow">01 / ECONOMIC OUTLOOK</div><h2>Weight the possibilities</h2></div><span className={`badge ${weightsError?'warn':'good'}`}>{Number.isFinite(totalWeight)?`${(totalWeight*100).toFixed(0)}% allocated`:'Incomplete weights'}</span></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Scenario</th><th>Weight %</th><th>PD ×</th><th>Scenario ECL</th></tr></thead><tbody>{scenarios.map(s=><tr key={s.id}><td><strong>{s.name}</strong></td><td><input aria-label={`${s.name} weight`} style={{ width:75 }} type="number" min={0} max={100} step={1} value={Number.isFinite(s.weight)?Number((s.weight*100).toFixed(3)):''} onChange={event=>updateScenario(s.id,'weight',event.target.value===''?NaN:Number(event.target.value)/100)}/></td><td><input aria-label={`${s.name} PD multiplier`} style={{ width:75 }} type="number" min={0} max={10} step={0.05} value={Number.isFinite(s.pdMultiplier)?s.pdMultiplier:''} onChange={event=>updateScenario(s.id,'pdMultiplier',event.target.value===''?NaN:Number(event.target.value))}/></td><td>{result?money(result.scenarios.find(v=>v.id===s.id)?.ecl||0):'—'}</td></tr>)}</tbody></table></div><p className="muted" style={{ fontSize:12, lineHeight:1.6 }}>Weights must total 100%. PD multipliers change the annual conditional probability; Stage 3 stays at 100%.</p></section>
    <section className="panel"><div className="panel-header"><div><div className="eyebrow">02 / STAGING PROFILE</div><h2>Where risk sits</h2></div><FileCheck2 size={20}/></div><div style={{ display:'grid',gap:22 }}>{[1,2,3].map(stage=>{const total=result?.stageTotals.find(s=>s.stage===stage);return <div key={stage}><div style={{ display:'flex',alignItems:'center',justifyContent:'space-between',gap:12,marginBottom:8 }}><span><span className={`badge ${stage===1?'good':stage===2?'warn':'bad'}`}>Stage {stage}</span> <small className="muted">{stage===1?'12-month ECL':stage===2?'Lifetime ECL':'Credit impaired'}</small></span><strong>{total?money(total.ecl):'—'}</strong></div><div className="bar-track"><div className="bar-fill" style={{width:`${result?.ead?100*(total?.ead||0)/result.ead:0}%`}}/></div><div className="muted" style={{fontSize:12,marginTop:6}}>{total?.count??'—'} facilities · {total?money(total.ead):'—'} EAD</div></div>})}</div></section></div>
    <section className="panel" style={{marginTop:20}}><div className="panel-header"><div><div className="eyebrow">03 / FACILITY REVIEW</div><h2>Follow the decision</h2></div><div style={{display:'flex',gap:8,alignItems:'center'}}><Search size={16}/><input aria-label="Search ECL facilities" placeholder="Borrower, sector or ID" value={search} onChange={event=>{setSearch(event.target.value);setPage(0)}}/></div></div><div className="tabs" aria-label="Stage filter">{[0,1,2,3].map(stage=><button key={stage} className={stageFilter===stage?'active':''} onClick={()=>{setStageFilter(stage);setPage(0)}}>{stage?`Stage ${stage}`:'All facilities'}</button>)}</div><div className="table-wrap" style={{marginTop:15}}><table className="data-table"><thead><tr><th>Facility / borrower</th><th>Stage</th><th>Days past due</th><th>EAD · USDm</th><th>Weighted ECL · USDm</th><th>Decision</th></tr></thead><tbody>{filtered.slice(safePage*8,safePage*8+8).map(f=><tr key={f.id} style={current?.id===f.id?{background:'var(--accent-soft, rgba(90,120,130,.07))'}:{}}><td><button className="btn" style={{padding:'4px 0',border:0,background:'transparent',textAlign:'left'}} onClick={()=>setSelected(f.id)}><span><strong>{f.borrower}</strong><small className="muted" style={{display:'block'}}>{f.id} · {f.sector}</small></span><ArrowRight size={14}/></button></td><td><span className={`badge ${f.stage===1?'good':f.stage===2?'warn':'bad'}`}>{f.stage}</span></td><td>{f.daysPastDue}</td><td>{f.ead.toFixed(2)}</td><td><strong>{f.weightedEcl.toFixed(3)}</strong></td><td style={{maxWidth:230,fontSize:12}}>{f.reasons.join(' · ')}</td></tr>)}{!filtered.length&&<tr><td colSpan={6} className="muted">{result?'No facilities match this view.':'Resolve the calculation inputs to review facilities.'}</td></tr>}</tbody></table></div><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginTop:14}}><small className="muted">{filtered.length} facilities · Page {safePage+1} of {Math.max(1,Math.ceil(filtered.length/8))}</small><div style={{display:'flex',gap:8}}><button className="btn" disabled={safePage===0} onClick={()=>setPage(safePage-1)}>Previous</button><button className="btn" disabled={(safePage+1)*8>=filtered.length} onClick={()=>setPage(safePage+1)}>Next</button></div></div></section>
    {current&&trace&&<section className="panel" style={{marginTop:20}}><div className="panel-header"><div><div className="eyebrow">04 / CALCULATION TRACE</div><h2>{current.borrower} <span className="muted" style={{fontSize:13,fontWeight:400}}> / {current.id}</span></h2></div><label style={{display:'flex',alignItems:'center',gap:8}}><select aria-label="Trace economic scenario" value={trace.id} onChange={event=>setScenarioId(event.target.value)}>{scenarios.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select><ChevronDown size={14}/></label></div><div className="notice" style={{marginBottom:16}}>EAD {money(trace.ead)} × LGD {pct(trace.lgd)} × each period’s marginal PD × discount factor. <strong>{trace.horizon.toFixed(1)} year</strong> horizon; <strong>{money(trace.ecl)}</strong> scenario ECL.</div><div className="table-wrap"><table className="data-table"><thead><tr><th>Time · years</th><th>Survival before</th><th>Marginal PD</th><th>EAD · USDm</th><th>Discount factor</th><th>ECL · USDm</th></tr></thead><tbody>{trace.periods.map(period=><tr key={period.year}><td>{period.time.toFixed(2)}</td><td>{pct(period.survival)}</td><td>{pct(period.marginalPd)}</td><td>{period.ead.toFixed(2)}</td><td>{period.discountFactor.toFixed(5)}</td><td>{period.loss.toFixed(5)}</td></tr>)}</tbody></table></div><p className="muted" style={{fontSize:12}}>Annual PD {pct(trace.annualPd)} · LGD {pct(trace.lgd)} · Effective annual rate {pct(current.rate)} · Constant EAD assumption</p></section>}
    <details className="panel" style={{marginTop:20}}><summary style={{cursor:'pointer',display:'flex',alignItems:'center',gap:9}}><Info size={17}/><strong>Staging policy, methodology & scope</strong></summary><div className="muted" style={{lineHeight:1.7,marginTop:16}}><p>The illustrative staging policy uses 90+ days past due for Stage 3, 31–89 days or a watchlist flag for Stage 2, and otherwise Stage 1. The worst stage propagates across the borrower’s facilities. Every trigger remains visible in the decision column.</p><p>EAD = drawn balance + undrawn × CCF. Annual conditional PD becomes survival-weighted marginal PD for each year; each loss is discounted at the effective annual rate. Stage 1 has a one-year horizon, Stage 2 a lifetime horizon, and Stage 3 has 100% PD in its first period. Fractional final years are supported.</p><p>This demonstration uses constant bullet EAD. It does not model amortization, collateral allocation, rating migration, cure periods or individual recovery cash flows. Its weights and calibrations are illustrative, and require independent approval before any financial reporting use. Theme selection never changes this calculation.</p></div></details>
  </>;
}
