import { useState } from 'react';
import { Download, FileText, Printer, ArrowUpRight, GitCompareArrows, X } from 'lucide-react';
import type { Workspace,Run,Page } from '../types';
import {downloadWorkbook} from '../lib/workbook-download';
import { download,downloadCSV } from '../lib/format';
import { PageHeader,Panel,Empty } from '../components/UI';
const summaryNumber=new Intl.NumberFormat('en-US',{maximumFractionDigits:3});
const jkbSummary:Record<string,{label:string;unit:'amount'|'fraction'|'count'}>={
 baselineEcl:{label:'Pre-shock ECL',unit:'amount'},stressedEcl:{label:'Post-shock ECL',unit:'amount'},incrementalEcl:{label:'ECL movement',unit:'amount'},
 capitalBefore:{label:'Pre-shock total capital',unit:'amount'},capitalAfter:{label:'Post-shock total capital',unit:'amount'},carBefore:{label:'Pre-shock capital adequacy ratio',unit:'fraction'},carAfter:{label:'Post-shock capital adequacy ratio',unit:'fraction'},
 cet1After:{label:'Post-shock CET1 capital',unit:'amount'},rwaAfter:{label:'Post-shock total RWA',unit:'amount'},lcrAfter:{label:'Post-shock liquidity coverage sensitivity',unit:'fraction'},nsfrAfter:{label:'Post-shock stable funding sensitivity',unit:'fraction'},
 pbtAfter:{label:'Post-shock profit before tax',unit:'amount'},profitImpact:{label:'Profit movement before tax',unit:'amount'},drawdown:{label:'Cash drawdown',unit:'amount'},withdrawal:{label:'Deposit withdrawal',unit:'amount'},checksPassed:{label:'Identity checks passed',unit:'count'},checksTotal:{label:'Identity checks assessed',unit:'count'},
};
const jkbAnalysis=(run:Run)=>(run.payload as any)?.analysis?.schema==='AVATI_JKB_STRESS_V1'?(run.payload as any).analysis:null;
const summaryLabel=(run:Run,key:string)=>jkbAnalysis(run)?jkbSummary[key]?.label||key:key;
function summaryValue(run:Run,key:string,value:unknown,difference=false){
 if(typeof value!=='number')return value==null?'Unavailable':String(value);
 const analysis=jkbAnalysis(run),unit=analysis?jkbSummary[key]?.unit:null;
 if(unit==='fraction')return `${(value*100).toFixed(2)}${difference?' pp':'%'}`;
 const formatted=summaryNumber.format(value);
 return unit==='amount'?`${formatted} ${analysis.units.currency} ${analysis.units.amountUnit}`:formatted;
}
export default function Reports({workspace:w,navigate}:{workspace:Workspace,navigate:(p:Page)=>void}){
 const [exportError,setExportError]=useState('');const [module,setModule]=useState('All modules'),[selected,setSelected]=useState<Run|null>(null),[compare,setCompare]=useState<string[]>([]);const runs=w.runs.filter(r=>module==='All modules'||r.module===module);const compared=w.runs.filter(r=>compare.includes(r.id));
 const pivotCompatible=compared.length!==2||compared[0].module!=='Pivot'||['source','dimension','measure','sector','unit','category'].every(k=>(compared[0].payload as any)?.analysis?.[k]===(compared[1].payload as any)?.analysis?.[k]);
 const stressCompatible=compared.length!==2||compared[0].module!=='Stress'||((compared[0].payload as any)?.analysis?.schema===(compared[1].payload as any)?.analysis?.schema&&['basis','currency','amountUnit'].every(k=>(compared[0].payload as any)?.analysis?.config?.[k]===(compared[1].payload as any)?.analysis?.config?.[k]));
 async function exportExcel(run:Run){try{setExportError('');const analysis=(run.payload as any).analysis;const flat=(rows:any[])=>rows.map(row=>Object.fromEntries(Object.entries(row).filter(([,v])=>v===null||['string','number','boolean'].includes(typeof v))));const sheets:{name:string;rows:Record<string,unknown>[]}[]=[{name:'Summary',rows:Object.entries(run.summary).map(([measure,value])=>({measure,value,module:run.module,bank:run.bank,portfolioVersion:run.portfolioVersion,capturedAt:run.date}))}];if(Array.isArray(analysis.facilities))sheets.push({name:'Facility results',rows:flat(analysis.facilities)});if(Array.isArray(analysis.checks))sheets.push({name:'Controls',rows:flat(analysis.checks)});if(Array.isArray(analysis.rows))sheets.push({name:'Stress metrics',rows:flat(analysis.rows)});if(Array.isArray(analysis.stages))sheets.push({name:'Stage transmission',rows:flat(analysis.stages)});if(Array.isArray(analysis.groups))sheets.push({name:'Pivot',rows:flat(analysis.groups)});await downloadWorkbook(sheets,run.bank,`avati-${run.module}-review.xlsx`);}catch(e){setExportError((e as Error).message);}}
 return <><PageHeader eyebrow="06 / Reports & review" title="An answer you can trace." description="Saved analyses preserve the portfolio, model settings and calculated results together." action={<button className="btn" disabled={!w.runs.length} onClick={()=>download('avati-review-pack.json',JSON.stringify({exportedAt:new Date().toISOString(),schemaVersion:1,bank:w.bank,runs:w.runs},null,2))}><Download size={16}/>Export review pack</button>}/><div className="report-banner"><FileText size={32}/><div><h2>From working analysis to review-ready evidence.</h2><p>Each capture records a point in time. Later portfolio changes keep earlier results intact.</p></div><span className="badge">{w.runs.length} saved runs</span></div>
 <Panel title="Analysis library" subtitle="Choose two runs from the same module to compare their summaries." action={<select aria-label="Report module filter" value={module} onChange={e=>setModule(e.target.value)}>{['All modules','RiskCube','ESG','Stress','ECL','Pivot'].map(m=><option key={m}>{m}</option>)}</select>}>
 {!runs.length?<Empty title="Your next insight belongs here." description="Run an ESG assessment, stress scenario, ECL calculation or pivot analysis, then save it to this library." action={<button className="btn primary" onClick={()=>navigate('stress')}>Open stress laboratory<ArrowUpRight size={16}/></button>}/>:<div className="report-list">{runs.map(r=><div className="report-row" key={r.id}><input type="checkbox" aria-label={`Compare ${r.name} ${r.id}`} checked={compare.includes(r.id)} onChange={()=>setCompare(c=>c.includes(r.id)?c.filter(id=>id!==r.id):c.length<2?[...c,r.id]:[c[1],r.id])}/><span className="report-icon"><FileText size={22}/></span><div><button className="table-link" onClick={()=>setSelected(r)}>{r.name}</button><p>{r.module} · {new Date(r.date).toLocaleString()} · {r.bank.toUpperCase()} · Portfolio v{r.portfolioVersion}</p></div><span className={`badge ${r.portfolioVersion===w.portfolioVersion?'good':'warn'}`}>{r.portfolioVersion===w.portfolioVersion?'Current portfolio':'Earlier portfolio'}</span><button className="btn small" onClick={()=>setSelected(r)}>Open<ArrowUpRight size={14}/></button></div>)}</div>}
 </Panel>{compared.length===2&&<Panel title="Run comparison" action={<GitCompareArrows size={20}/>}>{compared[0].module!==compared[1].module||!pivotCompatible||!stressCompatible?<p className="notice warn">Choose runs from the same module and model. Stress comparisons require matching currency, scale and basis; Pivot comparisons require matching source, grouping, measure, scope and unit filters.</p>:<><div className="table-wrap"><table className="data-table"><thead><tr><th>Measure</th><th>{compared[0].name}</th><th>{compared[1].name}</th><th>Difference (second − first)</th></tr></thead><tbody>{[...new Set(compared.flatMap(r=>Object.keys(r.summary)))].map(k=><tr key={k}><td>{summaryLabel(compared[0],k)}</td>{compared.map(r=><td key={r.id}>{summaryValue(r,k,r.summary[k]??'—')}</td>)}<td>{typeof compared[0].summary[k]==='number'&&typeof compared[1].summary[k]==='number'?summaryValue(compared[1],k,Number(compared[1].summary[k])-Number(compared[0].summary[k]),true):'—'}</td></tr>)}</tbody></table></div>{compared[0].portfolioVersion!==compared[1].portfolioVersion&&<p className="notice warn">These runs use different portfolio versions. Differences may include changes in portfolio inputs.</p>}</>}</Panel>}
 {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><section className="modal report-modal" role="dialog" aria-modal="true" aria-label="Saved analysis" onClick={e=>e.stopPropagation()}><div className="panel-header"><div><div className="eyebrow">AVATI / {selected.module} / Saved analysis</div><h2>{selected.name}</h2></div><button autoFocus className="icon-button no-print" aria-label="Close saved analysis" onClick={()=>setSelected(null)}><X/></button></div><p>{new Date(selected.date).toLocaleString()} · {selected.bank.toUpperCase()} · Portfolio v{selected.portfolioVersion}</p><div className="detail-grid">{Object.entries(selected.summary).map(([k,v])=><div key={k}><small>{summaryLabel(selected,k)}</small><strong>{summaryValue(selected,k,v)}</strong></div>)}</div>{exportError&&<p className="notice bad" role="alert">{exportError}</p>}<p className="notice">Illustrative analytical model. This locally saved record is a working-paper snapshot, not an authenticated approval or regulatory filing.</p><div className="button-row no-print"><button className="btn" onClick={()=>void exportExcel(selected)}><Download size={16}/>Excel review</button><button className="btn primary" onClick={()=>download(`avati-${selected.module}-${selected.id.slice(0,8)}.json`,JSON.stringify(selected,null,2))}><Download size={16}/>Full inputs & results</button><button className="btn" onClick={()=>downloadCSV('avati-summary.csv',Object.entries(selected.summary).map(([measure,value])=>({measure,value})))}>Summary CSV</button><button className="btn" onClick={()=>window.print()}><Printer size={16}/>Print summary</button></div></section></div>}
 </>;
}
