import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowRight,ArrowUpRight,Check,Download,FileSpreadsheet,Layers3,Search,Save,Upload} from 'lucide-react';
import type {ModuleProps} from '../types';
import {JKB_CASES,JKB_INPUT_FIELDS,DEFAULT_JKB_CONFIG,validateJKBConfig,runJKBStress} from '../lib/jkb-stress.mjs';
import {readJKBWorkbook,mapJKBCaseToConfig} from '../lib/jkb-workbook.mjs';
import {connectedContext} from '../lib/cube-context.mjs';
import {download,downloadCSV} from '../lib/format';
import {downloadWorkbook} from '../lib/workbook-download';
import {Metric,PageHeader,Panel} from '../components/UI';
import QuickStress from './QuickStress';
import JKBReconciliation from '../components/JKBReconciliation';
import JKBNativeCases from '../components/JKBNativeCases';
import JKBDepositors from '../components/JKBDepositors';

const severities=['MODERATE','MEDIUM','SEVERE'];
const comparisonColumns=[{key:'incrementalEcl',label:'ECL movement',unit:'amount'},{key:'carAfter',label:'Capital ratio',unit:'fraction'},{key:'lcrAfter',label:'LCR',unit:'fraction'},{key:'nsfrAfter',label:'NSFR',unit:'fraction'}];
const fmt=(v:unknown,unit='amount')=>typeof v!=='number'||!Number.isFinite(v)?'—':unit==='fraction'?`${(v*100).toFixed(2)}%`:v.toLocaleString('en-US',{maximumFractionDigits:2});
const fmtMovement=(v:unknown,unit:string)=>unit==='fraction'&&typeof v==='number'&&Number.isFinite(v)?`${(v*100).toFixed(2)} pp`:fmt(v,unit);
const clone=<T,>(v:T):T=>JSON.parse(JSON.stringify(v));
function NumberField({label,value,unit='amount',required=false,onChange}:{label:string;value:number;unit?:string;required?:boolean;onChange:(n:number)=>void}){const scale=unit==='fraction'?100:unit==='bps'?10000:1;return <label className={`field ${required&&!Number.isFinite(value)?'jkb-missing':''}`}>{label}{unit==='fraction'?' · %':unit==='bps'?' · bps':''}{required&&!Number.isFinite(value)&&<small>Required source input</small>}<input type="number" step={unit==='count'?1:'any'} value={Number.isFinite(value)?Number((value*scale).toFixed(8)):''} onChange={e=>onChange(e.target.value===''?NaN:Number(e.target.value)/scale)}/></label>}

export default function Stress(props:ModuleProps&{calibrationError?:string}){
 const {facilities,settings,saveSetting,onRun,bank,calibrationError=''}=props;
 const [mode,setMode]=useState('JKB workbench'),[tab,setTab]=useState('Scenario library'),[search,setSearch]=useState(''),[family,setFamily]=useState('All risks');
 const [config,setConfig]=useState<any>(()=>clone(settings.jkbStressConfig||DEFAULT_JKB_CONFIG)),[notice,setNotice]=useState(''),[error,setError]=useState(''),[saved,setSaved]=useState(false);
 const [workbook,setWorkbook]=useState<any>(settings.jkbWorkbook||null),[loading,setLoading]=useState(false),[nativeKey,setNativeKey]=useState(''),[currency,setCurrency]=useState('JOD'),[amountUnit,setAmountUnit]=useState('units');const fileInput=useRef<HTMLInputElement>(null);
 useEffect(()=>{setConfig(clone(settings.jkbStressConfig||DEFAULT_JKB_CONFIG));setSaved(false)},[settings.jkbStressConfig]);
 useEffect(()=>{setWorkbook(settings.jkbWorkbook||null)},[settings.jkbWorkbook]);useEffect(()=>{setSaved(false)},[props.portfolioVersion,settings.cubeProjection]);
 const calculated=useMemo(()=>{try{if(config.basis==='portfolio'&&calibrationError)throw Error(calibrationError);const cube=config.basis==='portfolio'?connectedContext(facilities,settings):{result:null,error:''};if(cube.error)throw Error(`Connected RiskCube run blocked: ${cube.error}`);return{result:runJKBStress(facilities,config,cube.result) as any,error:''}}catch(e){return{result:null,error:(e as Error).message}}},[facilities,config,settings,calibrationError]);
 const r=calculated.result,current:any=(JKB_CASES as any[]).find(c=>c.id===config.caseId)||(JKB_CASES as any[])[0];
 const shock={...current.shocks?.[config.severity],...config.overrides?.[current.id]?.[config.severity]};
 const shockKeys=current.id==='operational-loss'?['amount']:['credit-concentration','liquidity-concentration'].includes(current.id)?['numCustomers']:current.id==='profit-change'?['pct','amount']:['pct'];
 const visible=(JKB_CASES as any[]).filter(c=>(family==='All risks'||c.family===family)&&`${c.id} ${c.name} ${c.description}`.toLowerCase().includes(search.toLowerCase()));
 const nativeCase=workbook?.cases?.find((c:any)=>c.key===nativeKey);
 function update(next:any){setConfig(next);setSaved(false);setNotice('');try{const checked=validateJKBConfig(next);setConfig(checked);saveSetting('jkbStressConfig',checked);setError('')}catch(e){setError((e as Error).message)}}
 function field(key:string,value:number){update({...config,inputs:{...config.inputs,[key]:value},source:config.source?{...config.source,missingInputs:(config.source.missingInputs||[]).filter((k:string)=>k!==key||!Number.isFinite(value)),manualInputs:{...config.source.manualInputs,[key]:Number.isFinite(value)}}:null})}
 function setShock(key:string,value:number){update({...config,overrides:{...config.overrides,[current.id]:{...config.overrides?.[current.id],[config.severity]:{...shock,[key]:value}}}})}
 function capture(){if(!r)return;onRun({module:'Stress',name:`JKB · ${current.name} · ${config.severity}`,payload:r,summary:Object.fromEntries(Object.entries(r.summary).map(([k,v])=>[k,v==null?'Unavailable':v as string|number]))});setSaved(true)}
 async function exportReview(){if(!r)return;try{await downloadWorkbook([{name:'Scenario results',rows:r.rows},{name:'Controls',rows:r.checks},{name:'Severity comparison',rows:r.comparison.map((c:any)=>({severity:c.severity,...c.summary}))}],bank,'avati-jkb-stress-review.xlsx');setNotice('Excel review prepared.')}catch(e){setError((e as Error).message)}}
 async function readWorkbook(file:File){setLoading(true);setError('');try{const parsed=await readJKBWorkbook(await file.arrayBuffer(),{filename:file.name,currency,amountUnit});if(parsed.errors?.length)throw Error(parsed.errors.join(' '));setWorkbook(parsed);setNativeKey('');saveSetting('jkbWorkbook',parsed);if(config.source?.caseKey)update(clone(DEFAULT_JKB_CONFIG));setNotice('Workbook inspected. Select a source case and review its mapping. Any previous native selection has been cleared.')}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 async function applyNative(){if(!nativeCase)return;try{const mapped=mapJKBCaseToConfig(workbook,nativeKey,config);update(mapped);setTab('Pre-shock inputs')}catch(e){setError((e as Error).message)}}
 async function chooseSeverity(severity:string){
  if(config.source?.caseKey&&workbook){const s=config.source;const match=workbook.cases.find((c:any)=>c.asOf===s.asOf&&c.entity===s.entity&&c.scenarioId===s.scenarioId&&c.elementId===s.elementId&&c.severity===severity);if(!match){setError('This severity has no matching native case. Select an available workbook observation.');return}try{setNativeKey(match.key);update(mapJKBCaseToConfig(workbook,match.key,config))}catch(e){setError((e as Error).message)}}else update({...config,severity});
 }
 function chooseCase(caseId:string){if(config.source?.caseKey){setTab('Workbook bridge');setNotice('Select the native observation for this test; its scope and pre-shock inputs may differ.')}else update({...config,caseId})}
 return <><div className="stress-mode tabs" aria-label="Stress testing workspace">{['JKB workbench','Quick sensitivity'].map(m=><button key={m} className={mode===m?'active':''} onClick={()=>setMode(m)}>{m}</button>)}</div>{mode==='Quick sensitivity'?(calibrationError?<div className="notice bad" role="alert">RiskCube calibration blocked: {calibrationError}</div>:<QuickStress {...props}/>):<>
 <PageHeader eyebrow="JKB / STRESS TESTING WORKBENCH" title="Test the bank. Trace every impact." description="Credit, concentration, market, operational and liquidity tests, following the JKB tool’s case and calculation structure." action={<><button className="btn" disabled={!r} onClick={()=>void exportReview()}><Download size={16}/>Excel review</button><button className="btn primary" disabled={!r||!!error} onClick={capture}>{saved?<Check size={16}/>:<Save size={16}/>} {saved?'Assessment saved':'Save assessment'}</button></>}/>
 <div className="jkb-workflow">{['Source data','Pre-shock position','Scenario & severity','Post-shock metrics','Reconcile & review'].map((s,i)=><div key={s}><span>{String(i+1).padStart(2,'0')}</span><strong>{s}</strong>{i<4&&<ArrowRight size={16}/>}</div>)}</div>
 <div className="jkb-context"><span className="subtle-badge"><FileSpreadsheet size={15}/>{config.basis==='workbook'?`Workbook basis · ${config.currency} ${config.amountUnit}`:'Shared portfolio · USD millions'}</span><span>One as-of date · three independent severity cases</span><button className="text-button" onClick={()=>setTab('Workbook bridge')}>Open native workbook<ArrowUpRight size={14}/></button></div>
 <div className="tabs">{['Scenario library','Pre-shock inputs','Results & reconciliation','Workbook bridge'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div>
 {(error||calculated.error)&&<div role="alert" className="notice bad">{error||calculated.error} Invalid calculation inputs block results and capture.</div>}{notice&&<div className="notice" role="status">{notice}</div>}
 {tab!=='Workbook bridge'&&<div className="jkb-active-case"><div><span className="eyebrow">{current.family} / {current.id}</span><h2>{current.name}</h2></div><div className="jkb-severity" aria-label="JKB stress severity">{severities.map(s=><button key={s} aria-pressed={config.severity===s} className={config.severity===s?'active':''} onClick={()=>void chooseSeverity(s)}>{s.charAt(0)+s.slice(1).toLowerCase()}</button>)}</div></div>}
 {r&&tab!=='Workbook bridge'&&<div className="metrics"><Metric label="Post-shock capital ratio" value={fmt(r.stressed.car,'fraction')} detail={`CET1 ${fmt(r.stressed.cet1Ratio,'fraction')}`}/><Metric label="ECL movement" value={fmt(r.impact.ecl)} detail={r.units.currency+" "+r.units.amountUnit}/><Metric label="Liquidity coverage" value={fmt(r.stressed.lcr,'fraction')} detail={`From ${fmt(r.baseline.lcr,'fraction')}`}/><Metric label="Net stable funding" value={fmt(r.stressed.nsfr,'fraction')} detail={`From ${fmt(r.baseline.nsfr,'fraction')}`}/></div>}
 {tab==='Scenario library'&&<div className="jkb-library"><aside className="panel jkb-library-list"><label className="field">Find a stress test<div className="search-field"><Search size={16}/><input aria-label="Search JKB scenarios" placeholder="Credit, FX, runoff…" value={search} onChange={e=>setSearch(e.target.value)}/></div></label><label className="field">Risk family<select value={family} onChange={e=>setFamily(e.target.value)}><option>All risks</option>{[...new Set((JKB_CASES as any[]).map(c=>c.family))].map(f=><option key={f}>{f}</option>)}</select></label><div className="jkb-case-list">{visible.map(c=><button key={c.id} className={c.id===current.id?'active':''} onClick={()=>chooseCase(c.id)}><small>{c.family}</small><strong>{c.name}</strong><span>{c.id}<ArrowUpRight size={14}/></span></button>)}</div></aside><div className="jkb-library-detail"><Panel title={current.name} subtitle={current.description}><div className="jkb-source-line"><Layers3 size={17}/><span>Workbook calculation: {current.sourceSheet}</span></div><div className="form-grid"><label className="field">Portfolio scope<select value={config.sector||''} disabled={config.basis==='workbook'} onChange={e=>update({...config,sector:e.target.value})}><option value="">Whole portfolio</option>{[...new Set(facilities.map(f=>f.sector))].map(s=><option key={s}>{s}</option>)}</select></label>{shockKeys.map(k=><NumberField key={k} label={k==='pct'?'Shock size':k==='numCustomers'?'Number of customers':'Shock amount'} value={shock[k]} unit={k==='pct'?(current.shockUnit==='bps'?'bps':'fraction'):k==='numCustomers'?'count':'amount'} onChange={v=>setShock(k,v)}/>)}</div><p className="muted">{current.id==="operational-loss"?"A negative amount is a loss. ":current.id==="market-price"?"A negative percentage is a price decline. ":current.id==="market-fx"?"Positive means local currency appreciation; negative means depreciation. ":""}Each severity starts from the same pre-shock position. Overlapping scenario cases are not added together.</p><button className="text-button" onClick={()=>setTab('Pre-shock inputs')}>Review inputs for this test<ArrowRight size={15}/></button></Panel><Panel title="Three severities. One calculation." subtitle="Compare independent outcomes against the same starting position.">{r&&<div className="table-wrap"><table className="data-table"><thead><tr><th>Severity</th>{comparisonColumns.map(c=><th key={c.key}>{c.label}</th>)}</tr></thead><tbody>{r.comparison?.map((c:any)=><tr key={c.severity}><td><button className="table-link" onClick={()=>void chooseSeverity(c.severity)}>{c.severity}</button></td>{comparisonColumns.map(col=><td className="numeric" key={col.key} title={c.error||undefined}>{fmt(c.summary?.[col.key],col.unit)}</td>)}</tr>)}</tbody></table></div>}</Panel><div className="notice"><Activity size={18}/><span>13 configured shock types. Customer-specific limit drawdown and ALM factor revision require additional source rules.</span></div></div></div>}
 {tab==='Pre-shock inputs'&&<><Panel title="Choose the balance-sheet basis" subtitle="Facility credit connects to the portfolio; capital, P&L and liquidity need their own starting position."><button className="btn small" style={{marginBottom:20}} onClick={()=>update(clone({...DEFAULT_JKB_CONFIG,caseId:current.id,severity:config.severity}))}>Use synthetic starting position</button><div className="form-grid"><label className="field">Input basis<select value={config.basis} onChange={e=>update({...config,basis:e.target.value,currency:e.target.value==='portfolio'?'USD':config.currency,amountUnit:e.target.value==='portfolio'?'millions':config.amountUnit})}><option value="portfolio">Shared facilities · USD millions</option><option value="workbook">Native workbook / manual balance sheet</option></select></label>{config.basis==='workbook'&&<><label className="field">Currency<input value={config.currency} onChange={e=>update({...config,currency:e.target.value.toUpperCase()})}/></label><label className="field">Amount unit<select value={config.amountUnit} onChange={e=>update({...config,amountUnit:e.target.value})}>{['units','thousands','millions'].map(u=><option key={u}>{u}</option>)}</select></label></>}</div><p className="muted">Currency and scale identify the amounts; editing these labels does not convert values. Portfolio-derived credit fields are replaced by the shared facility calculation.</p></Panel>{[...new Set((JKB_INPUT_FIELDS as any[]).map(f=>f.group))].filter(group=>config.basis!=="portfolio"||group!=="Native credit").map(group=><Panel key={group} title={group} subtitle="Editable starting values; changed inputs recalculate every severity."><div className="form-grid">{(JKB_INPUT_FIELDS as any[]).filter(f=>f.group===group).map(f=><NumberField key={f.key} label={f.label} unit={f.unit} required={config.source?.missingInputs?.includes(f.key)} value={config.inputs?.[f.key]} onChange={v=>field(f.key,v)}/>)}</div></Panel>)}</>}
 {tab==='Results & reconciliation'&&r&&<><Panel title="Pre-shock → shock → post-shock" subtitle="Calculation steps retain their native workbook references." action={<button className="btn small" onClick={()=>downloadCSV('avati-jkb-stress-results.csv',r.rows)}><Download size={15}/>CSV</button>}><div className="table-wrap"><table className="data-table"><thead><tr><th>Metric</th><th>Pre-shock</th><th>Shock</th><th>Post-shock</th><th>Movement</th><th>Calculation / source</th></tr></thead><tbody>{r.rows.map((row:any)=><tr key={row.id}><td>{row.label}</td><td className="numeric">{fmt(row.preShock,row.unit)}</td><td className="numeric">{fmtMovement(row.shock,row.unit)}</td><td className="numeric">{fmt(row.postShock,row.unit)}</td><td className="numeric">{fmtMovement(row.delta,row.unit)}</td><td><span>{row.formula}</span><small>{row.sourceRef}</small></td></tr>)}</tbody></table></div></Panel>{r.stages?.length>0&&<Panel title="Credit stage transmission" subtitle="Exposure, ECL and credit RWA before and after the shock."><div className="table-wrap"><table className="data-table"><thead><tr><th>Stage</th><th>Exposure before</th><th>Exposure after</th><th>ECL before</th><th>ECL after</th><th>RWA before</th><th>RWA after</th></tr></thead><tbody>{r.stages.map((s:any)=><tr key={s.stage}><td>Stage {s.stage}</td>{['exposureBefore','exposureAfter','eclBefore','eclAfter','rwaBefore','rwaAfter'].map(k=><td className="numeric" key={k}>{fmt(s[k])}</td>)}</tr>)}</tbody></table></div></Panel>}<Panel title="Reconciliation identities" subtitle="Checks observe the calculation; missing source values remain missing."><div className="table-wrap"><table className="data-table"><thead><tr><th>Control</th><th>Expected</th><th>Actual</th><th>Difference</th><th>Status</th></tr></thead><tbody>{r.checks.map((c:any)=><tr key={c.id}><td>{c.label}</td><td>{fmt(c.expected)}</td><td>{fmt(c.actual)}</td><td>{fmt(c.difference)}</td><td><span className={`badge ${c.status==='PASS'?'good':'bad'}`}>{c.status}</span></td></tr>)}</tbody></table></div></Panel>{r.warnings?.length>0&&<div className="notice warn">{r.warnings.map((w:string)=><p key={w}>{w}</p>)}</div>}<button className="btn" onClick={()=>download('avati-jkb-stress.json',JSON.stringify(r,null,2))}>Export complete calculation<Download size={16}/></button></>}
 {tab==='Workbook bridge'&&<><Panel title="Bring in the native JKB workbook" subtitle="Inspect scenarios, pre-shock data and stored system outputs locally. VBA macros are not executed."><div className="form-grid"><label className="field">Source amount currency<input value={currency} maxLength={3} onChange={e=>setCurrency(e.target.value.toUpperCase())}/></label><label className="field">Source amount unit<select value={amountUnit} onChange={e=>setAmountUnit(e.target.value)}>{['units','thousands','millions'].map(u=><option key={u}>{u}</option>)}</select></label></div><input className="sr-only" type="file" accept=".xlsx,.xlsm" ref={fileInput} aria-label="Import JKB stress workbook" onChange={e=>{if(e.target.files?.[0])void readWorkbook(e.target.files[0]);e.target.value='';}}/><div className="jkb-import-card"><FileSpreadsheet size={34}/><div><h3>JKB Stress Testing · VBA & Builds</h3><p>Read the native Scenario Element Output schema. Confirm its currency and scale above before loading.</p></div><button className="btn primary" disabled={loading} onClick={()=>fileInput.current?.click()}><Upload size={16}/>{loading?'Reading workbook…':'Load JKB workbook'}</button></div></Panel>{workbook&&<Panel title={workbook.source?.filename||'Imported workbook'} subtitle={`${workbook.cases?.length||0} cases · ${workbook.source?.currency||''} ${workbook.source?.amountUnit||''} · source snapshots`}><JKBNativeCases cases={workbook.cases||[]} value={nativeKey} onChange={setNativeKey}/>{nativeCase&&<><div className="notice">{nativeCase.elementType} · {Object.keys(nativeCase.inputs||{}).length} mapped inputs{nativeCase.missingInputs?.length?` · Missing: ${nativeCase.missingInputs.join(', ')}`:''}</div><div className="table-wrap"><table className="data-table"><thead><tr><th>Input</th><th>Value</th><th>Source cell</th></tr></thead><tbody>{Object.entries(nativeCase.inputs||{}).map(([k,v])=><tr key={k}><td>{k}</td><td>{fmt(v)}</td><td>{nativeCase.provenance?.[k]}</td></tr>)}</tbody></table></div><button className="btn primary" onClick={()=>void applyNative()}>Apply mapped case<ArrowRight size={16}/></button></>}{workbook.warnings?.map((w:string)=><p className="notice warn" key={w}>{w}</p>)}</Panel>}</>}
 {tab==="Workbook bridge"&&nativeCase&&<Panel title="Stored system output" subtitle="Native system snapshot for the selected case. These values are controls; they are not recalculated by the browser."><div className="table-wrap"><table className="data-table"><thead><tr><th>Native output</th><th>Stored value</th></tr></thead><tbody>{Object.entries(workbook.outputs?.find((o:any)=>o.caseKey===nativeKey)?.values||{}).map(([key,value])=><tr key={key}><td>{key}</td><td className="numeric">{fmt(value)}</td></tr>)}</tbody></table></div></Panel>}
 {tab==="Results & reconciliation"&&r&&<JKBReconciliation assessment={r} workbook={workbook}/>}
 {tab==="Pre-shock inputs"&&config.basis==="portfolio"&&<JKBDepositors rows={config.depositors||[]} onChange={rows=>update({...config,depositors:rows})}/>}
 </>}</>;
}
