import { useState,useEffect,useRef } from 'react';
import { LayoutDashboard, Boxes, Database, Leaf, Activity, ShieldCheck, Grid2X2, Files, Search, ChevronDown, Check, Download, Upload, X, ArrowUpRight, History, Monitor, Info, Menu, AlertTriangle } from 'lucide-react';
import type { Bank,Page,Workspace,Run,Facility } from './types';
import { loadWorkspace,STORAGE_KEY,validateWorkspace,uid,now } from './lib/store';
import {riskInputs} from './lib/cube-context.mjs';
import { download } from './lib/format';
import Desk from './pages/Desk';
import Cube from './pages/Cube';
import Portfolio from './pages/Portfolio';
import ESG from './pages/ESG';
import Stress from './pages/Stress';
import ECL from './pages/ECL';
import Pivot from './pages/Pivot';
import Reports from './pages/Reports';
import { PageHeader,Panel } from './components/UI';
const banks:Record<Bank,{name:string,full:string,style:string}>={midbank:{name:'MIDBANK',full:'Midbank · Cairo',style:'Emerald desk'},jkb:{name:'JKB',full:'Jordan Kuwait Bank',style:'Light blue'},nbi:{name:'NBI',full:'National Bank of Iraq',style:'Midnight & gold'},jcb:{name:'JCB',full:'Jordan Commercial Bank',style:'Ivory & teal'}};
const nav:{id:Page,label:string,icon:typeof LayoutDashboard}[]=[{id:'desk',label:'The desk',icon:LayoutDashboard},{id:'cube',label:'RiskCube',icon:Boxes},{id:'portfolio',label:'Portfolio',icon:Database},{id:'esg',label:'ESG',icon:Leaf},{id:'stress',label:'Stress lab',icon:Activity},{id:'ecl',label:'IFRS 9',icon:ShieldCheck},{id:'pivot',label:'Pivot Desk',icon:Grid2X2},{id:'reports',label:'Reports',icon:Files}];
function initialPage():Page{const p=location.hash.slice(1) as Page;return [...nav.map(n=>n.id),'activity'].includes(p)?p:'desk';}
export default function App(){
 const [initial]=useState(loadWorkspace),[w,setW]=useState<Workspace>(initial.workspace),[page,setPage]=useState<Page>(initialPage),[bankMenu,setBankMenu]=useState(false),[command,setCommand]=useState(false),[query,setQuery]=useState(''),[notice,setNotice]=useState(''),[storageError,setStorageError]=useState(initial.error||''),[pendingImport,setPendingImport]=useState<Workspace|null>(null),[help,setHelp]=useState(false),[mobileNav,setMobileNav]=useState(false);const restore=useRef<HTMLInputElement>(null);const canSave=useRef(!initial.error);
 useEffect(()=>{document.documentElement.dataset.bank=w.bank;document.documentElement.style.colorScheme=w.bank==='jkb'||w.bank==='jcb'?'light':'dark';},[w.bank]);
 useEffect(()=>{if(!canSave.current)return;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(w));setStorageError('');}catch{setStorageError('Storage is full or unavailable. Export a workspace backup now to preserve your changes.');}},[w]);
 useEffect(()=>{const h=()=>setPage(initialPage());window.addEventListener('hashchange',h);const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();setCommand(c=>!c);}if(e.key==='Escape'){setCommand(false);setBankMenu(false);setHelp(false);setPendingImport(null);}};window.addEventListener('keydown',key);return()=>{window.removeEventListener('hashchange',h);window.removeEventListener('keydown',key);}},[]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(timer);},[notice]);
 function navigate(p:Page){setPage(p);location.hash=p;setCommand(false);setMobileNav(false);window.scrollTo({top:0,behavior:'smooth'});}
 function change(update:(old:Workspace)=>Workspace,action:string,detail:string){setW(old=>{const next=update(old);return {...next,events:[{id:uid(),date:now(),action,detail},...next.events].slice(0,500)};});}
 const saveSetting=(key:string,value:unknown)=>change(old=>({...old,settings:{...old.settings,[key]:value}}),'Model settings updated',key);
 function onRun(run:Omit<Run,'id'|'date'|'bank'|'portfolioVersion'>){change(old=>{const captured:Run=JSON.parse(JSON.stringify({...run,id:uid(),date:now(),bank:old.bank,portfolioVersion:old.portfolioVersion,payload:{modelVersion:'avati-1.0',analysis:run.payload,portfolio:old.facilities,settings:old.settings}}));return {...old,runs:[captured,...old.runs]};},'Analysis captured',`${run.module} · ${run.name}`);setNotice('Analysis saved. Open Reports to review or export it.');}
 const calibrated=riskInputs(w.facilities,w.settings);const props={facilities:w.facilities,bank:w.bank,portfolioVersion:w.portfolioVersion,settings:w.settings,saveSetting,onRun};
 const replace=(facilities:Facility[],detail:string)=>{change(old=>({...old,facilities,portfolioVersion:old.portfolioVersion+1}),'Portfolio replaced',detail);setNotice('Portfolio updated across every module. Earlier reports remain unchanged.');};
 async function importBackup(file:File){try{if(file.size>15_000_000)throw Error('Choose a workspace backup under 15 MB.');setPendingImport(validateWorkspace(JSON.parse(await file.text())));}catch(e){setNotice(`Import failed: ${(e as Error).message}`);}}
 return <div className="app"><a className="skip-link" href="#main-content">Skip to content</a><header className="app-header"><button className="brand" aria-label="Avati home" onClick={()=>navigate('desk')}><span className="brand-word">AVATI</span><span className="brand-divider"/><span className="brand-product">RISK STUDIO<small>CONNECTED INTELLIGENCE</small></span></button><nav className={`main-nav ${mobileNav?'mobile-open':''}`} aria-label="Main navigation">{nav.map(n=><button key={n.id} aria-current={page===n.id?'page':undefined} className={page===n.id?'active':''} onClick={()=>navigate(n.id)}><n.icon size={16}/><span>{n.label}</span></button>)}</nav><div className="header-actions"><button className="icon-button mobile-menu" aria-label="Toggle navigation" onClick={()=>setMobileNav(v=>!v)}><Menu size={21}/></button><button className="bank-switch" aria-label="Choose bank theme" aria-expanded={bankMenu} onClick={()=>setBankMenu(!bankMenu)}><span className="bank-monogram">{banks[w.bank].name.slice(0,1)}</span><span>{banks[w.bank].name}<small>{banks[w.bank].style}</small></span><ChevronDown size={14}/></button></div></header>
 <div className="utility-bar"><div className="breadcrumbs"><span>Workspace</span><span>/</span><strong>{page==='activity'?'Activity & lineage':nav.find(n=>n.id===page)?.label}</strong></div><div><span className="save-status"><span className={`live-dot ${storageError?'warning':''}`}/>{storageError?'Backup needed':'Saved on this device'}</span><button className="command-trigger" onClick={()=>{setQuery('');setCommand(true);}}><Search size={14}/><span>Jump to…</span><kbd>Ctrl K</kbd></button><button className="icon-button" aria-label="Activity and workspace tools" onClick={()=>navigate('activity')}><History size={17}/></button><button className="icon-button" aria-label="About this workspace" onClick={()=>setHelp(true)}><Info size={17}/></button></div></div>
 {storageError&&<div className="storage-alert" role="alert"><AlertTriangle size={18}/>{storageError}<button className="btn small" onClick={()=>download('avati-workspace-recovery.json',JSON.stringify(w,null,2))}>Export backup</button></div>}
 <main id="main-content" className="main-content" key={page}>{['esg','stress','ecl','pivot'].includes(page)&&<div className="connected-module-bar"><span><Boxes size={17}/>{calibrated.bridge?.valid?'RiskCube annual PD calibration connected':'Part of the connected RiskCube workflow'}</span><button className="text-button" onClick={()=>navigate('cube')}>Open connected run<ArrowUpRight size={14}/></button></div>}{page==='desk'?<Desk workspace={w} navigate={navigate}/>:page==='cube'?<Cube {...props} navigate={navigate}/>:page==='portfolio'?<Portfolio facilities={w.facilities} onReplace={replace} version={w.portfolioVersion} bank={w.bank}/>:page==='esg'?<ESG {...props}/>:page==='stress'?(calibrated.error?<div role="alert" className="notice bad">RiskCube calibration blocked: {calibrated.error}</div>:<Stress {...props} facilities={calibrated.facilities}/>):page==='ecl'?(calibrated.error?<div role="alert" className="notice bad">RiskCube calibration blocked: {calibrated.error}</div>:<ECL {...props} facilities={calibrated.facilities}/>):page==='pivot'?<Pivot {...props}/>:page==='reports'?<Reports workspace={w} navigate={navigate}/>:<><PageHeader eyebrow="07 / Workspace lineage" title="The story behind the numbers." description="A local activity log of portfolio changes, model assumptions and captured analyses." action={<><button className="btn" onClick={()=>restore.current?.click()}><Upload size={16}/>Restore workspace</button><button className="btn primary" onClick={()=>download('avati-workspace.json',JSON.stringify(w,null,2))}><Download size={16}/>Backup workspace</button></>}/><div className="notice"><Monitor size={20}/><span>This workspace is stored in this browser on this device. The activity log supports your working papers; it is not an immutable server audit or a maker/checker approval record.</span></div><Panel title="Activity log" subtitle={`${w.events.length} events retained · most recent first`}><div className="activity-list">{w.events.map(e=><div className="activity-row" key={e.id}><span className="activity-dot"/><div><strong>{e.action}</strong><p>{e.detail}</p></div><time>{new Date(e.date).toLocaleString()}</time></div>)}</div></Panel></>}</main>
 <footer className="app-footer"><span>AVATI <i>Risk Studio 1.0</i></span><span>{banks[w.bank].full} theme · Model settings remain independent</span><button onClick={()=>setHelp(true)}>Method & workspace notes<ArrowUpRight size={13}/></button></footer>
 <input className="sr-only" ref={restore} type="file" accept=".json,application/json" aria-label="Restore workspace JSON" onChange={e=>{if(e.target.files?.[0])void importBackup(e.target.files[0]);e.target.value='';}}/>
 {bankMenu&&<><div className="dismiss-layer" onClick={()=>setBankMenu(false)}/><section className="bank-menu" role="dialog" aria-label="Bank themes"><div className="eyebrow">Make it your bank</div><h3>A complete experience.</h3><p>Every page, chart and control follows your theme.</p>{(Object.keys(banks) as Bank[]).map(b=><button className={`bank-option ${w.bank===b?'selected':''}`} key={b} onClick={()=>{change(old=>({...old,bank:b}),'Theme changed',banks[b].full);setBankMenu(false);}}><span className={`theme-swatch ${b}`}><i/><i/><i/></span><span><strong>{banks[b].full}</strong><small>{banks[b].style}</small></span>{w.bank===b&&<Check size={17}/>}</button>)}<small>Bank themes are visual presets, not approved bank configurations.</small></section></>}
 {command&&<div className="modal-backdrop" onClick={()=>setCommand(false)}><div className="command-modal" role="dialog" aria-modal="true" aria-label="Jump to a module" onClick={e=>e.stopPropagation()}><label className="command-input"><Search/><input autoFocus placeholder="Where would you like to go?" value={query} onChange={e=>setQuery(e.target.value)}/><button className="icon-button" aria-label="Close search" onClick={()=>setCommand(false)}><X/></button></label>{nav.filter(n=>`${n.label} ${n.id}`.toLowerCase().includes(query.toLowerCase())).map(n=><button className="command-result" key={n.id} onClick={()=>navigate(n.id)}><n.icon size={20}/><span>{n.label}</span><ArrowUpRight size={16}/></button>)}</div></div>}
 {pendingImport&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="Restore workspace"><div className="eyebrow">Workspace restore</div><h2>Replace the current workspace?</h2><p>This backup contains {pendingImport.facilities.length} facilities and {pendingImport.runs.length} saved analyses. Export your current workspace first if you want to keep it.</p><div className="button-row"><button className="btn" onClick={()=>download('avati-before-restore.json',JSON.stringify(w,null,2))}>Export current</button><button className="btn primary" onClick={()=>{canSave.current=true;setW({...pendingImport,events:[{id:uid(),date:now(),action:'Workspace restored',detail:'Validated JSON backup restored'},...pendingImport.events].slice(0,500)});setPendingImport(null);setNotice('Workspace restored successfully.');}}>Restore backup</button><button className="btn" onClick={()=>setPendingImport(null)}>Cancel</button></div></section></div>}
 {help&&<div className="modal-backdrop" onClick={()=>setHelp(false)}><section className="modal" role="dialog" aria-modal="true" aria-label="Workspace notes" onClick={e=>e.stopPropagation()}><div className="panel-header"><div><div className="eyebrow">AVATI / Risk Studio</div><h2>Connected by design.</h2></div><button autoFocus className="icon-button" aria-label="Close workspace notes" onClick={()=>setHelp(false)}><X/></button></div><p>A working analytical application inspired by the Avati ESG framework, Midbank PivotDesk, JKB/JCB stress workbenches and NBI IFRS 9 requirements.</p><div className="note-block"><h3>One master. Separate conclusions.</h3><p>Your portfolio connects the modules. ESG assessments, stress losses and reporting ECL keep their own assumptions and outputs.</p><h3>Transparent model boundaries.</h3><p>The supplied models and synthetic data support exploration and implementation review. Bank use requires calibrated PD/LGD, approved policies, full cashflow models and independent validation. No regulatory compliance or filing approval is implied.</p><h3>Local, portable and reviewable.</h3><p>Data stays in this browser. Export JSON backups and saved run inputs for reproducibility. Enterprise authentication, encrypted server storage and governed approvals are not part of this local edition.</p></div><button className="btn primary" onClick={()=>setHelp(false)}>Back to the workspace</button></section></div>}
 {notice&&<div className="toast" role="status"><Check size={18}/><span>{notice}</span><button className="icon-button" aria-label="Dismiss notification" onClick={()=>setNotice('')}><X size={16}/></button></div>}
 </div>;
}
